export const Data = [
  {
    id: 1,
    name: "Add Fund",
    path: "/funds/addfunds",
    icon: "fa-solid fa-money-bill-transfer",
    description: "You can add funds to Your Wallet",
  },
  {
    id: 1,
    name: "Withdraw Fund",
    path: "/funds/withdrawfund",
    icon: "fa-solid fa-money-bill-transfer",
    description: "You can add funds to the user account",
  },
  {
    id: 1,
    name: "Approved Deposit History",
    path: "/funds/approveddeposithistory",
    icon: "fa-solid fa-money-bill-transfer",
    description: "You can add funds to the user account ",
  },
  {
    id: 1,
    name: "Approved Withdrawal History",
    path: "/funds/approvedwithdrawalhistory",
    icon: "fa-solid fa-money-bill-transfer",
    description: "You can add funds to the user account ",
  },
  {
    id: 1,
    name: "Fund Request History",
    path: "/funds/fundrequesthistory",
    icon: "fa-solid fa-clock-rotate-left",
    description: "You can add funds to the user account ",
  },
  {
    id: 1,
    name: "Add Bank Details",
    path: "/funds/addbankdetails",
    icon: "fa-solid fa-landmark",
    description: "You can add funds to the user account ",
  },
  // {
  //   id: 1,
  //   name: "Add Fund via Payment Gatway",
  //   path: "/admin/funds/addfunds",
  //   icon: "fa-solid fa-dollar-sign",
  //   description: "You can add funds to Your Wallet",
  // },
  // {
  //   id: 1,
  //   name: "Add  Manual Deposite Slip",
  //   path: "/admin/funds/addfunds",
  //   icon: "fa-solid fa-file-invoice-dollar",
  //   description: "You can add manual deposite slip",
  // },
];
